name: A workflow for my Hello World file

on: push https://github.com/dwambia/hello-github-actions/tree/dwambia-patch-1
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
