name: A workflow for my Hello World file

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - dwambia-patch-1
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
